# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reverb Consulting | Digital Marketing | Funnel Development | Automating Operations
email: thomas@reverbconsulting.com
description: |-
  We look at your whole customer life-cycle. We track a customer all the away
  from initial awarness, to a repeat customer who refers you. We do this by using
  many different digital marketing tools and automating your operations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reverbconsulting.com" # the base hostname & protocol for your site
twitter_username: reverbconsult
keywords: digital marketing,funnel development,operational automation
# Build settings
port: 8080
markdown: kramdown
logo: assets/images/RVC_Logo_RGB.svg
